### ISSUE TITLE
Localstorage vs SessionStorage

### ISSUE THREAD

**Issue by MiaoXiao** [MiaoXiao/CS100-Music-Game-#1]
For storing the volume and the current difficulty, shouldn't we use a session storage object instead of a local storage object? If we store that data in a session storage object, that data is wiped every time the tab is closed and reopened, which is what we would probably want for the volume and current difficulty variables.

What we should rather store in local storage is all the statistics, since we want the user to be able to check that whenever they want, even if they close the browser. We should actually use local storage instead of cookies for this.

I was just reading this: http://www.w3schools.com/html/html5_webstorage.asp

Let me know what you guys think.

**Comment by scohe001** [comment]
Now that we're combining everything into a single html, we may not need to use local storage at all. As long as we can keep the variables in our JavaScript's separate.

**Comment by scohe001** [comment]
*session storage

I agree that we can store stats in local storage.
